import os

from pyspark.sql.functions import (
    col,
    lower,
    trim,
    regexp_replace,
    format_string,
    round,
    concat_ws,
    lit,
    broadcast,
)

from sparkutils import get_spark, resolve_data_path, read_table, write_table, apply_local_spark_defaults


def normalize_station_name(column):
    return lower(
        trim(
            regexp_replace(
                regexp_replace(
                    regexp_replace(column, r"\s+", " "),
                    r"\s*/\s*",
                    " / ",
                ),
                r"\s*-\s*",
                "-",
            )
        )
    )



def main():
    spark = get_spark()
    apply_local_spark_defaults(spark)
    # spark.conf.set("spark.sql.files.maxRecordsPerFile", "500000")
    MAXRECORDSPERFILE = int(os.environ.get("AUGMENT_MAX_RECORDS_PER_FILE", "100000"))

    base_path = resolve_data_path()
    # if os.environ.get("DATABRICKS_RUNTIME_VERSION"):
    #     default_format = "delta"
    # else:
    #     default_format = "parquet"

    default_format = "parquet"
    read_format = default_format
    write_format = default_format

    if os.environ.get("DATABRICKS_RUNTIME_VERSION"):
        write_format = "delta"
        table_location = "workspace.`bixi-fs`"

    # storage_format = os.environ.get("SILVER_STORAGE_FORMAT", default_format)
    
    rides_stage_path = f"{base_path}/silver/rides_stage"
    rides_final_path = f"{base_path}/silver/rides"
    if write_format == "delta":
        rides_final_path = f"{table_location}.`silver-rides`"
    station_cleaning_base = f"{base_path}/silver/station_cleaning"
    # Use station mapping produced by stage 2b script (unsuffixed output paths)
    mapping_csv_path = f"{station_cleaning_base}/station_direct_match_mapping_csv"
    mapping_table_path = f"{station_cleaning_base}/station_direct_match_mapping"
    h3_mapping_csv_path = f"{station_cleaning_base}/station_canonical_h3_mapping_csv"
    h3_mapping_table_path = f"{station_cleaning_base}/station_canonical_h3_mapping"

    silver_rides_df = read_table(spark, rides_stage_path, read_format)

    # Prefer parquet table over CSV for better performance
    if os.path.exists(mapping_table_path):
        mapping_df = (
            read_table(spark, mapping_table_path, read_format)
            .select("station_key", "canonical_station_id", "canonical_lat", "canonical_lon", "normalized_name")
            .dropDuplicates(["station_key"])
        )
        print(f"Using mapping source (parquet): {mapping_table_path}")
    elif os.path.exists(mapping_csv_path):
        mapping_df = (
            spark.read.option("header", True)
            .csv(mapping_csv_path)
            .select("station_key", "canonical_station_id")
            .dropDuplicates(["station_key"])
        )
        print(f"Using mapping source (CSV fallback): {mapping_csv_path}")
    else:
        raise FileNotFoundError(f"Mapping not found at {mapping_table_path} or {mapping_csv_path}")

    # Load canonical_station_id -> H3 mapping generated by stage 3.
    if os.path.exists(h3_mapping_table_path):
        h3_mapping_df = (
            read_table(spark, h3_mapping_table_path, read_format)
            .select("canonical_station_id", "h3_cell", "h3_resolution")
            .dropDuplicates(["canonical_station_id"])
        )
        print(f"Using H3 mapping source (parquet): {h3_mapping_table_path}")
    elif os.path.exists(h3_mapping_csv_path):
        h3_csv_df = spark.read.option("header", True).csv(h3_mapping_csv_path)
        h3_cols = set(h3_csv_df.columns)
        if "canonical_station_id" not in h3_cols or "h3_cell" not in h3_cols:
            raise ValueError(
                f"H3 mapping CSV missing required columns at {h3_mapping_csv_path}"
            )
        if "h3_resolution" in h3_cols:
            h3_mapping_df = h3_csv_df.select("canonical_station_id", "h3_cell", "h3_resolution")
        else:
            h3_mapping_df = h3_csv_df.select("canonical_station_id", "h3_cell").withColumn("h3_resolution", lit(None).cast("int"))
        h3_mapping_df = h3_mapping_df.dropDuplicates(["canonical_station_id"])
        print(f"Using H3 mapping source (CSV fallback): {h3_mapping_csv_path}")
    else:
        raise FileNotFoundError(
            f"H3 mapping not found at {h3_mapping_table_path} or {h3_mapping_csv_path}. "
            "Run stage 03_build_station_h3_mapping.py first."
        )

    keyed_rides_df = (
        silver_rides_df
        .withColumn("start_station_name_norm", normalize_station_name(col("start_station_name")))
        .withColumn("end_station_name_norm", normalize_station_name(col("end_station_name")))
        .withColumn(
            "start_coord_key",
            format_string(
                "%.6f,%.6f",
                round(col("start_station_latitude"), 6),
                round(col("start_station_longitude"), 6),
            ),
        )
        .withColumn(
            "end_coord_key",
            format_string(
                "%.6f,%.6f",
                round(col("end_station_latitude"), 6),
                round(col("end_station_longitude"), 6),
            ),
        )
        .withColumn("start_station_key", concat_ws("|", col("start_coord_key"), col("start_station_name_norm")))
        .withColumn("end_station_key", concat_ws("|", col("end_coord_key"), col("end_station_name_norm")))
    )

    start_map_df = mapping_df.select(
        col("station_key").alias("start_station_key"),
        col("canonical_station_id").alias("start_canonical_station_id"),
    )
    end_map_df = mapping_df.select(
        col("station_key").alias("end_station_key"),
        col("canonical_station_id").alias("end_canonical_station_id"),
    )

    start_h3_df = h3_mapping_df.select(
        col("canonical_station_id").alias("start_canonical_station_id"),
        col("h3_cell").alias("start_h3_cell"),
        col("h3_resolution").alias("start_h3_resolution"),
    )
    end_h3_df = h3_mapping_df.select(
        col("canonical_station_id").alias("end_canonical_station_id"),
        col("h3_cell").alias("end_h3_cell"),
        col("h3_resolution").alias("end_h3_resolution"),
    )

    # Mapping tables are small relative to rides; broadcast them to avoid large shuffle joins.
    augmented_df = keyed_rides_df.join(broadcast(start_map_df), on="start_station_key", how="left").join(
        broadcast(end_map_df), on="end_station_key", how="left"
    )
    augmented_df = augmented_df.join(
        broadcast(start_h3_df), on="start_canonical_station_id", how="left"
    ).join(
        broadcast(end_h3_df), on="end_canonical_station_id", how="left"
    )

    # Do not force a high repartition by default; it can trigger OOM in local mode.
    target_repartition = int(os.environ.get("AUGMENT_REPARTITION_PARTITIONS", "0"))
    if target_repartition > 0:
        augmented_df = augmented_df.repartition(target_repartition, col("ride_year"))
    ## TEMP
    # augmented_df = augmented_df.filter(col("ride_year") == 2026)

    write_table(augmented_df, rides_final_path, write_format, partition_cols=["ride_year"], maxRecordsPerFile=MAXRECORDSPERFILE)
    # if table_format:
    #     write_table(augmented_df, rides_final_table, table_format, partition_cols=["ride_year"], maxRecordsPerFile=MAXRECORDSPERFILE)
    # else:
    #     write_table(augmented_df, rides_final_path, storage_format, partition_cols=["ride_year"], maxRecordsPerFile=MAXRECORDSPERFILE)


    total_rows = augmented_df.count()
    start_unmapped_rows = augmented_df.filter(col("start_canonical_station_id").isNull()).count()
    end_unmapped_rows = augmented_df.filter(col("end_canonical_station_id").isNull()).count()
    start_h3_unmapped_rows = augmented_df.filter(col("start_h3_cell").isNull()).count()
    end_h3_unmapped_rows = augmented_df.filter(col("end_h3_cell").isNull()).count()

    start_mapped_rows = total_rows - start_unmapped_rows
    end_mapped_rows = total_rows - end_unmapped_rows
    start_h3_mapped_rows = total_rows - start_h3_unmapped_rows
    end_h3_mapped_rows = total_rows - end_h3_unmapped_rows

    start_mapping_rate = (start_mapped_rows / total_rows * 100.0) if total_rows else 0.0
    end_mapping_rate = (end_mapped_rows / total_rows * 100.0) if total_rows else 0.0
    start_h3_mapping_rate = (start_h3_mapped_rows / total_rows * 100.0) if total_rows else 0.0
    end_h3_mapping_rate = (end_h3_mapped_rows / total_rows * 100.0) if total_rows else 0.0

    print("=== Stage 4 complete: augment silver rides with station + H3 mapping ===")
    print(f"Storage format: {write_format}")
    print(f"spark.sql.shuffle.partitions: {spark.conf.get('spark.sql.shuffle.partitions')}")
    print(f"spark.sql.files.maxPartitionBytes: {spark.conf.get('spark.sql.files.maxPartitionBytes')}")
    print(f"spark.sql.parquet.enableVectorizedReader: {spark.conf.get('spark.sql.parquet.enableVectorizedReader')}")
    print(f"Max records per file: {MAXRECORDSPERFILE}")
    print(f"Rides source path: {rides_stage_path}")
    print(f"Mapping source: {mapping_table_path} or {mapping_csv_path}")
    print(f"H3 mapping source: {h3_mapping_table_path} or {h3_mapping_csv_path}")
    print(f"Rides final path: {rides_final_path}")
    print(f"Total rides checked: {total_rows:,}")
    print(f"Start mapping rate: {start_mapped_rows:,}/{total_rows:,} ({start_mapping_rate:.4f}%)")
    print(f"End mapping rate:   {end_mapped_rows:,}/{total_rows:,} ({end_mapping_rate:.4f}%)")
    print(f"Start H3 rate:      {start_h3_mapped_rows:,}/{total_rows:,} ({start_h3_mapping_rate:.4f}%)")
    print(f"End H3 rate:        {end_h3_mapped_rows:,}/{total_rows:,} ({end_h3_mapping_rate:.4f}%)")

    spark.stop()


if __name__ == "__main__":
    main()
